# -*- coding: utf-8 -*-
"""pca-vs-ica.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L1aUeyi8in_u_mKE_SVS2em4JlmtEhOB
"""

from google.colab import files 
  
  
uploaded = files.upload()

import pandas as pd 
import numpy
import seaborn as sns
import io 
  
df = pd.read_csv(io.BytesIO(uploaded['EEG-DATA-1.csv'])) 
print(df)

sns.pairplot(df)

df.describe

from sklearn.decomposition import PCA

data = PCA(n_components = 0.9)

data.fit(df)

data.n_components_

dataa = data.transform(df)
dataa =pd.DataFrame(dataa)
dataa

sns.pairplot(dataa)

print(data.components_)

import matplotlib.pyplot as plt

filas = 3
columnas = data.n_components_

plt.plot(range(len(data.explained_variance_)), data.explained_variance_ratio_)
plt.show()

plt.joinplot()

data2 = PCA(n_components = 0.85)

data2.fit(df)

data2.n_components_

dataa2 = data2.transform(df)
dataa2 =pd.DataFrame(dataa2)
sns.pairplot(dataa2)

print(data2.components_)

from sklearn.decomposition import FastICA

transformer = FastICA()
X_transformed = transformer.fit_transform(df)
X_transformed.shape

X_transformed = transformer.fit_transform(dataa2)
X_transformed.shape

X_transformed =pd.DataFrame(X_transformed)
dataa
sns.pairplot(X_transformed)